feat: add the `RpcClient`
decentraland/rpc-rust pull request #17
Opened 2023-01-02 11:52 UTC by lauti7

This PR:
- replaces`MemoryTransport`'s Tokio channels with `async-channels` crate because Tokio `Receiver::recv` receives `&mut self`
- simplifies parsing message function using generics
- new connection function to pass to a "connected" state between server<>client
- **add the RpcClient**

2023-01-02 17:51 UTC, guidota requested changes
Excellent work! :rocket:  Just a few comments

2023-01-02 17:51 UTC, guidota commented on src/client.rs
> +                    transport.establish_connection();
shouldn't we keep the trait as minimal as possible without exposing this flag setter?

I think it would be better to don't have this one for other transport implementations

2023-01-02 17:51 UTC, guidota commented on src/client.rs
> +                if let TransportEvent::Connect = response {
maybe we can be more specific on the pattern matching and do something like:

 ```suggestion
            Ok(TransportEvent::Connect) => {
```

2023-01-02 17:51 UTC, guidota commented on src/transports/memory.rs
> +                self.receiver.close();
```suggestion
                self.close();
```

2023-01-02 17:51 UTC, guidota commented on src/transports/memory.rs
> +        self.receiver.close();
Is not a change in this PR but should we set `self.connected = false` here?

2023-01-02 17:51 UTC, guidota commented on src/transports/mod.rs
> +    fn establish_connection(&mut self);
same as before, wouldn't be better to keep this method out of the trait?

2023-01-02 17:52 UTC, guidota commented on src/transports/memory.rs
> +        self.receiver.close();
Also, if it's async, do we need to add an `await` to the close?

2023-01-02 21:04 UTC, lauti7 commented on src/client.rs
> +        println!("Client IsConnected: {}", transport.is_connected());
just for debugging, im removing this

2023-01-02 21:04 UTC, lauti7 commented on src/client.rs
> +            .map_err(|err| err)
nope, removing it

2023-01-02 21:12 UTC, lauti7 commented on src/client.rs
> +                    transport.establish_connection();
Yes, I agree with you but as we use a trait for transports, we should use setters & getters for modifying a flag or field in a struct (transport).  I did this in this way because I don't want the `Transport::receive` method to be mutable. Anyway, I am open to modifying this!

2023-01-02 21:13 UTC, lauti7 commented on src/client.rs
> +                if let TransportEvent::Connect = response {
Cool, didn't know this syntax!

2023-01-02 21:20 UTC, lauti7 commented on src/transports/memory.rs
> +        self.receiver.close();
yes, u r right - I think we need a refactor here because `close` is called from `receive` which I prefer to keep not mutable and `close` need to be mutable so that it can mutate `self.connected`

2023-01-02 21:21 UTC, lauti7 commented on src/transports/mod.rs
> +    fn establish_connection(&mut self);
let's look into this

2023-01-02 21:23 UTC, lauti7 commented on src/transports/memory.rs
> +        self.receiver.close();
or we can put connected inside a Mutex :)

2023-01-03 12:58 UTC, guidota approved these changes

2023-01-04 22:04 UTC, merged