fix: import google empty
decentraland/rpc-rust pull request #64
Opened 2023-03-16 14:59 UTC by agusaldasoro

2023-03-16 15:30 UTC, agusaldasoro commented
Closing as the solution for that is to copy local the Google Protobuf definitions

2023-03-17 13:03 UTC, lauti7 commented on rpc_codegen/src/lib.rs
> +            quote! { () }
it's not so idiomatic to use the unit tuple. In fact, Clippy will suggest you remove it because it's actually unneeded. Could you replace it with an empty space?

2023-03-17 13:10 UTC, lauti7 requested changes
Great work, thx for taking over it! Some reqs and please fix the Clippy wanings on CI

2023-03-17 13:10 UTC, lauti7 commented on rpc_codegen/src/lib.rs
> +        let output_type = if method.output_type.to_string().eq("()") {
it's not so idiomatic to use the unit tuple as an output. In fact, Clippy will suggest you remove it because it's actually unneeded. Why don't make the function have no response?

2023-03-17 13:10 UTC, lauti7 commented on rpc_codegen/src/lib.rs
> +            quote! { () }
The same as the output type here. Maybe it's not needed to make the function have an argument which it's actually nothing.

2023-03-17 13:10 UTC, lauti7 commented on rpc_codegen/src/lib.rs
> +        let input_type = if method.input_type.to_string().eq("()") {
it would be cool to add some comments on why we are doing this over this line

2023-03-20 11:57 UTC, Julieta11 reviewed
Looks good! and nice refactor btw 🙌🏼

2023-03-20 14:48 UTC, lauti7 approved these changes
Great work! 💯

2023-03-20 14:48 UTC, lauti7 commented on examples/integration/src/service/book_service.rs
> +    async fn send_book(&self, _book: Book, _ctx: Arc<MyExampleContext>) {
You could push the received Book into the Books' array 👀

2023-03-20 20:40 UTC, merged