Add TLS support
decentraland/rpc-rust pull request #73
Opened 2023-04-10 21:50 UTC by agusaldasoro

2023-04-14 19:34 UTC, lauti7 requested changes
great 👍 just one comment

2023-04-14 19:34 UTC, lauti7 commented on Cargo.toml
>  quinn = "*"
Add back the QUIC example to the integration example. The error on compiling is here. It has to have the same version (`*` isn't a concrete version) as the `rpc`'s Cargo.toml.

2023-04-17 11:39 UTC, agusaldasoro commented on Cargo.toml
>  quinn = "*"
Great, I resetted the last commit and push force as it was the easiest way to undo the changes

2023-04-24 14:11 UTC, lauti7 approved these changes

2023-04-24 15:57 UTC, merged